### ISSUE TITLE
HW1#) qemu clone problem

### ISSUE THREAD

**Issue by 2020147584** [csi2115-f21/scripts#15]
After cloning qemu in /scripts, I realized that I should move upper directory. How can I fix it?

**Comment by programmer-k** [comment]
You could use the command `mv`.

**Comment by 2020147584** [comment]
Thanks for your help!

**Comment by 2020147584** [comment]
Sorry, but I got another problem when execute `./build-qemu.sh ../qemu`

> realpath: ./build/qemu: No such file or directory
> mkdir: cannot create directory ‘/install’: Permission denied
> ./build-qemu.sh: line 25: pushd: no other directory
> + /mnt/c/Users/FAMILY/qemu/configure --prefix=/install --target-list=x86_64-softmmu --disable-werror
> 
> ERROR: pkg-config binary 'pkg-config' not found

I tried 
`sudo su`
`apt install pkg-config`
`apt --fix-broken install`

but nothing change... Do you know how to fix it?

**Comment by programmer-k** [comment]
@2020147584 
Please refer to the [following answer](https://github.com/csi2115-f21/scripts/issues/16#issuecomment-913666819) that I wrote.

**Comment by 2020147584** [comment]
it doesn't work...ㅠㅠ

**Comment by programmer-k** [comment]
@2020147584 
Can you again show the error message?
Is it different from the previous one?

**Comment by 2020147584** [comment]
![111](https://user-images.githubusercontent.com/80634727/132232329-2fc9dce6-54ba-4e22-8c79-492fd0dfe847.PNG)

**Comment by 2020147584** [comment]
![11111](https://user-images.githubusercontent.com/80634727/132232714-9218bfda-d0d4-4405-83c2-a3d476822cd8.PNG)

**Comment by programmer-k** [comment]
Hmm.. so the `realpath` problem still exists..
Firstly, can you run the following command?
```
sudo apt install pkg-config
```

**Comment by 2020147584** [comment]
Thanks a lot! It worked!
But after that, I faced 2 more problems.
First one was

>  ERROR: glib-2.48 gthread-2.0 is required to compile QEMU
and I fixed it with ` sudo apt-get install libglib2.0`
And now there's

> ERROR: meson setup failed
...I think it's better to start over ㅜㅜ

**Comment by 2020147584** [comment]
I'm running the three codes now!

**Comment by programmer-k** [comment]
@2020147584 
Good!

**Comment by 2020147584** [comment]
After third code, I'm now executing `./build-qemu ~ ` but it takes a long time.

**Comment by programmer-k** [comment]
@2020147584 
Congratulations!
Now I will close this issue.
