### ISSUE TITLE
HW#1) fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by camillejin** [csi2115-f21/scripts#16]
When I run `./build-qemu.sh ../qemu` , I get 

> realpath: ./build/qemu: No such file or directory                                                           mkdir: cannot create directory ‘/install’: Permission denied                                              ./build-qemu.sh: line 25: pushd: no other directory                                                         + /mnt/c/Users/alice/qemu/configure --prefix=/install --target-list=x86_64-softmmu --disable-werror  

but then it continues to run and ends with the below message.

> [1/18] Generating qemu-version.h with a meson_exe.py custom command                                         fatal: No names found, cannot describe anything.                                                            [1/2] Installing files.                                                                                     Error getting authority: Error initializing authority: Could not connect: No such file or directory         FAILED: meson-install                                                                                       /usr/bin/python3 /mnt/c/Users/alice/qemu/meson/meson.py install --no-rebuild                                ninja: build stopped: subcommand failed.                                                                    make: *** [Makefile:152: run-ninja] Error 1 

Does anyone have the same issue? Or have figured out a solution for this error??

**Comment by programmer-k** [comment]
For the first error related to realpath, you can use the following command to solve.

**Comment by camillejin** [comment]
@programmer-k 
I have tried that and got this message:

> -bash: /home/cami/scripts$: No such file or directory

**Comment by programmer-k** [comment]
Umm. Sorry.
Can you try this one?
```
mkdir -p ./build/qemu
```

**Comment by camillejin** [comment]
> Sorry for the hassle.
> Can you try this one?
> 
> ```
> mkdir -p ./build/qemu
> ```

@programmer-k 

This worked! Thanks a lot! 
I'll try to figure out why the second error occurred and add it to the thread if I find out more.

**Comment by programmer-k** [comment]
@camillejin 
Great! Please go ahead and let me know if you have any problems.
If I could not help, someone else also can join and help.

**Comment by camillejin** [comment]
It seems like the second issue disappears with the first one if you create a build directory.

**Comment by programmer-k** [comment]
@camillejin 
Great! I seems that the problem has been solved, so I will close this issue.
