### ISSUE TITLE
HW#1 error building linux kernel

### ISSUE THREAD

**Issue by vikiminki** [csi2115-f21/scripts#17]
I am running into this when trying to build the linux kernel. Anyone knows how to solve it? 
<img width="610" alt="cantfindconfig" src="https://user-images.githubusercontent.com/17335838/132229487-1788fda9-c1aa-4dd4-85db-5d8c4909ee59.png">

**Comment by vikiminki** [comment]
Okay nvm I had to just copy and rename the x86_64_defconfig to the name given in the script for this error...

**Comment by hwgyun** [comment]
Did you download "scripts" before 9/4 and download "linux" after 9/4?
In this case, this problem happend because on 9/4, the "linux" and "scripts" are changed.
I suggest that re-clone the "scripts".
Because, x86_64_defconfig and csi...defconfig file are quite different.

**Comment by vikiminki** [comment]
Oh didnt realize the repo had been updated. Thanks
