### ISSUE TITLE
Error when running ./build-qemu.sh ../qemu (meson set up failed)

### ISSUE THREAD

**Issue by sssm12** [csi2115-f21/scripts#36]
I'm having this error while running ./build-qemu.sh ../qemu which I haven't seen anyone posted about. 

Program @INPUT@ found: NO

../../../qemu/target/hexagon/meson.build:33:0: ERROR: Program '@INPUT@' not found

A full log can be found at /mnt/c/Users/sekmo/scripts/build/qemu/meson-logs/meson-log.txt

ERROR: meson setup failed

Can anyone help me?

**Comment by michaelp3** [comment]
Can you post the full log at /mnt/c/Users/sekmo/scripts/build/qemu/meson-logs/meson-log.txt?

**Comment by sssm12** [comment]
> /mnt/c/Users/sekmo/scripts/build/qemu/meson-logs/meson-log.txt
Sure!
[meson-log.txt](https://github.com/csi2115-f21/scripts/files/7128712/meson-log.txt)

**Comment by michaelp3** [comment]
Did you install libglib2.0 with `$ sudo apt install -y libglib2.0-dev`
and pixman-1 with `$ sudo apt install -y libpixman-1-dev`
I'm not really sure what the error is but I found a link [https://bbs.huaweicloud.com/forum/thread-120468-1-1.html](url)
that has a similar symptom to yours. The website is in Chinese but if you see the comment in the website it mentions something about pixman-1. Maybe that's the problem?

**Comment by sssm12** [comment]
I already installed both but the error happened after I did something with the root path. :(
