### ISSUE TITLE
HW#1) Error ~mounted with noexec or nodev when run ./create-image.sh 

### ISSUE THREAD

**Issue by happygeon** [csi2115-f21/scripts#41]
Also, I saw another issue because of the same error, but I couldn't solve it.
`mknod: /mnt/c/home/username/scripts/chroot/test-dev-null: Operation not supported`
`E: Cannot install into target '/mnt/c/home/username/scripts/chroot' mounted with noexec or nodev`
According to an external source, it is mentioned that it can be solved through `sudo mount -i -o remount,exec,dev /mnt/c.`
However, unlike external sources, in our case, we cannot run "umount or remount" because we did not mount.
Therefore, in my case, I didn't get an error through this code.
`sudo mount /dev/sda ./chroot`
run in sripts folder. sda means first device(usually c drive) you can choose device in /dev folder

Additional) Or you can do all steps on ~/.
It means, if your dir is /mnt/c/.... , error can be occur at this point.
Just do `cd ~/` and do again to first step of hw pdf.

**Comment by sssm12** [comment]
After doing this, I get another error 
rm: cannot remove 'chroot/file': Operation not permitted
Was it the same for you?

**Comment by happygeon** [comment]
If you mount, chroot is link to sda.
So when `rm -rf $DIR` which in create-image.sh file is run, it occur error.
I think that solution of this situation is edit file "create-image.sh".
Specifically, Add `sudo umount $DIR` in before the `sudo rm -rf $DIR` and add `sudo mount /dev/sda $DIR`(Or similar) after the`sudo chmod 0755 $DIR`.

**Comment by sssm12** [comment]
Sorry but how do I edit create-image.sh file?

**Comment by happygeon** [comment]
Additionally, you can open and edit the file with the 우클릭 -> 연결프로그램 -> 메모장.

**Comment by sssm12** [comment]
I did what you said and then it ended with this 
cp: cannot create directory '/mnt/chroot/././lib64': No space left on device many times
I did df -h and found that 
/dev/loop0 filesystem is used 100%

**Comment by happygeon** [comment]
Additional) Or you can do all steps on ~/.
It means, if your dir is /mnt/c/.... , error can be occur at this point.
Just do `cd ~/` and do again to first step of hw pdf.

**Comment by sssm12** [comment]
I think the mount comment earlier messed up my code. I uninstalled Ubuntu and redid the whole thing again and I passed this step without any issue. I'm gonna close this now.
