### ISSUE TITLE
./build-linux.sh ../linux doesn't end.

### ISSUE THREAD

**Issue by 2019147558** [csi2115-f21/scripts#47]
I made 16GB swap file and used the command 'sudo chmod 600 /swapfile', too. 
But it doesn't end.

~/linux ~/scripts
+ export CC=gcc-8
+ CC=gcc-8
+ export CXX=g++-8
+ CXX=g++-8
+ make csi2115_f21_defconfig O=/home/name/scripts/./build/linux/csi2115_f21
make[1]: Entering directory '/home/name/scripts/build/linux/csi2115_f21'
  GEN     Makefile
arch/x86/configs/csi2115_f21_defconfig:8430:warning: symbol value 'y' invalid for KASAN_STACK
#
# configuration written to .config
#
make[1]: Leaving directory '/home/name/scripts/build/linux/csi2115_f21'
+ make -j8 O=/home/name/scripts/./build/linux/csi2115_f21 CC=gcc-8
make[1]: Entering directory '/home/name/scripts/build/linux/csi2115_f21'
  SYNC    include/config/auto.conf.cmd
  GEN     Makefile
  GEN     Makefile
  DESCEND  objtool
  DESCEND  bpf/resolve_btfids
  CALL    /home/name/linux/scripts/atomic/check-atomics.sh
  CALL    /home/name/linux/scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  GZIP    kernel/config_data.gz
  CC      kernel/configs.o
  AR      kernel/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.a
  LD      vmlinux.o

It is not going on anymore.
When I entered ctrl+c, these messages appeared.
make[1]: *** [/home/name/linux/Makefile:1197: vmlinux] Interrupt
make: *** [Makefile:215: __sub-make] Interrupt

**Comment by Tim3s** [comment]
I think you already solved the problem, and I think it just takes very long time due to your computer's specification. Just don't enter ctrl+c, if the error is due to swap file problem (or RAM capacity), it will output an error itself.
